# Generated by Django 5.1.1 on 2024-11-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('idauth', models.AutoField(db_column='idAuth', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CantidadClasesDisciplina',
            fields=[
                ('id_cantidad_clases_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_clases', models.IntegerField()),
            ],
            options={
                'db_table': 'cantidad_clases_disciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id_clase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_clase', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'clases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=80)),
                ('apellido_paterno', models.CharField(max_length=45)),
                ('apellido_materno', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=45)),
                ('ocupacion', models.CharField(max_length=45)),
                ('fecha_de_nacimiento', models.DateField()),
                ('biometria_facial', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientasHasClases',
            fields=[
                ('id_clientaclase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_clase', models.CharField(blank=True, max_length=45, null=True)),
                ('presente', models.IntegerField(blank=True, null=True)),
                ('hora_llegada', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientas_has_clases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientasHasDisciplinas',
            fields=[
                ('id_clienta_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_disciplina_contratada', models.CharField(blank=True, max_length=120, null=True)),
                ('duracion_disciplina', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inscripcion', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.CharField(blank=True, max_length=45, null=True)),
                ('estado_membresia', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientas_has_disciplinas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactoDeEmergencia',
            fields=[
                ('id_contacto_emergencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_contacto_emergencia', models.CharField(max_length=80)),
                ('numero_contacto_emergencia', models.CharField(max_length=25)),
                ('correo_contacto_emergencia', models.CharField(max_length=120)),
                ('tipo_contacto_emergencia', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'contacto_de_emergencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_disciplina', models.CharField(blank=True, max_length=120, null=True)),
                ('descripcion_disciplina', models.TextField(blank=True, null=True)),
                ('rango_horarios', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'disciplinas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_estado_civil', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_estado_civil', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estado_civil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialMedicoClientas',
            fields=[
                ('id_historial_medico', models.AutoField(primary_key=True, serialize=False)),
                ('tiene_alergias', models.IntegerField()),
                ('detalle_alergia', models.TextField(blank=True, null=True)),
                ('tiene_cirugias', models.IntegerField()),
                ('detalle_cirugia', models.TextField(blank=True, null=True)),
                ('tiene_enfermedades', models.IntegerField()),
                ('detalle_enfermedad', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historial_medico_clientas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorariosClase',
            fields=[
                ('idhorarios', models.AutoField(db_column='idHorarios', primary_key=True, serialize=False)),
                ('fecha_clase', models.DateField()),
                ('hora_inicio', models.CharField(blank=True, max_length=10, null=True)),
                ('hora_fin', models.CharField(blank=True, max_length=10, null=True)),
                ('cupo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'horarios_clase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructores',
            fields=[
                ('id_instructor', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=80)),
                ('apellido_paterno', models.CharField(max_length=80)),
                ('apellido_materno', models.CharField(max_length=80)),
                ('esta_activo', models.IntegerField()),
            ],
            options={
                'db_table': 'instructores',
                'managed': False,
            },
        ),
    ]
